
FROM python:3.6

VOLUME /app
ADD requirements.txt /app/
COPY src/ /app/
WORKDIR /app
RUN pip3 install -r requirements.txt

EXPOSE 9003 # inutile

CMD ["python", "frontend.py", "apiuser", "apiarp"]

#docker build -t python-barcode .