version: "3"
services:

  tokendealer:
    image: tokendealer
    build: ./TokenDealer

  apiarp:
    image: apiarp
    build: ./ApiArp
    ports:
      - "5001:5001"
      - "9001:9001"

  apiuser:
    image: apiuser
    build: ./ApiUser
    ports:
      - "5002:5002"
      - "9002:9002"
    links:
      - db
    depends_on:
      - db

  frontend:
    image: frontend
    build: ./FrontEnd
    ports:
      - "5003:5003"
      - "9003:9003"

  db:
    image: mongo:3.0.2