
FROM python:3.6

VOLUME /app
ADD /src/* /app/
ADD requirements.txt /app/
WORKDIR /app
RUN pip3 install -r requirements.txt

EXPOSE 9002

CMD ["python", "user.py", "tokendealer", "db"]

#docker build -t python-barcode .
